services:
  - type: web
    name: reachinbox-email-scheduler
    runtime: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: |
      cd frontend && npm ci && npm run build
      cd ../backend && npm ci && npx prisma db push && npx prisma generate && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 10000
        sync: false
      - key: FRONTEND_URL
        value: "true"
        sync: false
      - key: JWT_SECRET
        value: ""
        sync: false
      - key: DATABASE_URL
        value: ""
        sync: false
      - key: REDIS_URL
        value: ""
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: "659048347978-5799lqskfg0l2bstaut2a2m41eftclm0.apps.googleusercontent.com"
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        value: ""
        sync: false